language: java
jdk:
  - openjdk8

branches:
  only:
    - aws_version
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - soccer6504@gmail.com

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: yourminemarket-travisci-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Kminseung/YourMineMarket-deploy #Github 주소
      branch: aws_version